version: "3.5"
 
services:
  central-server:
    container_name: xroad_sc
    image: niis/xroad-central-server:bionic-6.24.1
    ports:
      - "4000:4000"
      - "4001:80"
      - "4002:9998"
    networks:
      x-road-network:
        ipv4_address: 172.25.0.2
  transito-security-server:
    container_name: transito_ss
    image: niis/xroad-security-server:bionic-6.24.1
    ports:
      - "4100:4000"
      - "4101:80"
    networks:
      x-road-network:
        ipv4_address: 172.25.0.3
  tecnologia-security-server:
    container_name: tecnologia_ss
    image: niis/xroad-security-server:bionic-6.24.1
    ports:
      - "4200:4000"
      - "4201:80"
    networks:
      x-road-network:
        ipv4_address: 172.25.0.4
  transito_db:
    container_name: transito_db
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    networks:
      x-road-network:
        ipv4_address: 172.25.0.6
    restart: unless-stopped
  transito_si:
    build: 
      context: .
      dockerfile: transito_si/Dockerfile
    container_name: transito_si
    ports:
      - "1002:8080"
    depends_on:
      - "transito_db" 
    networks:
      x-road-network:
        ipv4_address: 172.25.0.5
    restart: unless-stopped
    
networks:
  x-road-network:
    name: x-road-network
    driver: bridge
    internal: false
    ipam:
      driver: default
      config:
      - subnet: 172.25.0.0/24