version: '3.5'

services:
  postgres:
    container_name: postgres_container_unal
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  runt:
    container_name: runt_service_unal
    build: .
    ports:
      - "1002:8080"
    depends_on:
      - "postgres" 
    networks:
      - postgres
    restart: unless-stopped
networks:
  postgres:
